functions.cpp
globals global
Referenced by calculate, calculationResult, getCleanInput, getRawInput, isValidFirst, isValidInput, isValidPar, isValidSyntax, renderCalculationProgress, renderGUI, tokenize.
string to_string128(__float128 value, int precision=40)
Converts __float128 to formatted string.
value 128-bit floating point value precision Decimal places to display (default: 40) Formatted string representation Uses quadmath library for precise string conversion of high-precision values.
Referenced by calculate.
void dividedZero()
Handles division by zero errors with tracking.
Records error occurrence for potential witty user feedback and outputs error information to stderr.
Referenced by calculate.
void getRawInput()
Ensures expression has outer parentheses for consistent parsing.
Adds surrounding parentheses if not present, simplifying the recursive parsing algorithm by guaranteeing parenthetical structure.
References global.
Referenced by calculationResult.
void getCleanInput()
Removes all whitespace characters from input expression.
Strips space, horizontal tab, newline, vertical tab, form feed, and carriage return using isspace() to prepare clean input for character-by-character parsing.
References global.
Referenced by calculationResult.
bool isValidFirst()
Validates expression starting character.
true if first character follows mathematical grammar rules
References global, invalidFirst.
Referenced by isValidInput.
bool isValidPar()
Ensures balanced parentheses throughout expression.
true if all parentheses are properly matched and nested
References global.
Referenced by isValidInput.
bool isValidSyntax()
Validates complete mathematical expression syntax.
true if expression follows proper mathematical grammar
References binary_minus, close_par, decimal, fractional, global, minus, number, open_par, operator_, start, unary_minus, variable.
Referenced by isValidInput.
bool isValidInput()
Comprehensive input validation pipeline.
true if input passes character, syntax, and structure validation Combines all validation functions to ensure safe processing of mathematical expressions before tokenization and calculation.
References global, isValidFirst, isValidPar, isValidSyntax, validList.
Referenced by calculationResult.
void tokenize()
Converts cleaned input into mathematical operation tokens.
Parses expression into array of numbers, operators, and parentheses. Handles implicit multiplication (e.g., "2(3)" → "2 \* 3"), converts unary minus to negative numbers, and validates decimal formatting. Does not support factorial (!) or variables (x,y,z) in current version
References global, operatorList.
Referenced by calculationResult.
void calculate()
Evaluates tokenized expression using operator precedence.
Processes tokens in mathematical order: Innermost parentheses first Exponentiation (^) - right associative Multiplication/Division ( * ,/) - left associative Addition/Subtraction (+,-) - left associative Uses 128-bit floating point throughout for maximum precision. Handles division by zero with error reporting.
References dividedZero, global, to_string128.
Referenced by calculationResult.
void renderCalculationProgress()
Renders real-time calculation progress in ImGui.
Displays phase-appropriate progress information including progress bars for long calculations.
References calculating, complete, error, global, validating, verifying.
string calculationTimeFormat(chrono::microseconds &duration)
Formats calculation duration with appropriate time units.
duration Elapsed time in microseconds Human-readable time string (µs, ms, or s) Automatically selects optimal units: microseconds (<1ms), milliseconds (<1s), or seconds with 2 decimal places.
Referenced by calculationResult.
void calculationResult()
Main calculation orchestrator function.
Orchestrates complete calculation workflow. Coordinates the complete calculation workflow: Input processing and cleaning Validation of mathematical expression Tokenization and parsing High-precision calculation Result formatting and timing Cleans up context after processing.
References calculate, calculationTimeFormat, getCleanInput, getRawInput, global, isValidInput, start, tokenize.
Referenced by renderGUI.
void renderGUI()
Implements main calculator interface layout.
Main application GUI renderer. Creates fixed-size window with multiline input field, calculate button, and result display area. Handles user interaction events and triggers calculation workflow.
References calculationResult, global, windowHeight, windowWidth.
Referenced by main.