functions.h
state
phase
const string validList
Parser configuration constants and validation sets.
Character sets for input validation, window dimensions, and global state management for the calculation workflow.
Referenced by isValidInput.
const string invalidFirst
Referenced by isValidFirst.
const string operatorList
Referenced by tokenize.
int screenRatioMultiplier
int windowWidth
Referenced by main, renderGUI.
int windowHeight
Referenced by main, renderGUI.
bool isValidFirst()
Validates expression starting character.
true if first character follows mathematical grammar rules
References global, invalidFirst.
Referenced by isValidInput.
bool isValidPar()
Ensures balanced parentheses throughout expression.
true if all parentheses are properly matched and nested
References global.
Referenced by isValidInput.
bool isValidSyntax()
Validates complete mathematical expression syntax.
true if expression follows proper mathematical grammar
References binary_minus, close_par, decimal, fractional, global, minus, number, open_par, operator_, start, unary_minus, variable.
Referenced by isValidInput.
bool isValidInput()
Comprehensive input validation pipeline.
true if input passes character, syntax, and structure validation Combines all validation functions to ensure safe processing of mathematical expressions before tokenization and calculation.
References global, isValidFirst, isValidPar, isValidSyntax, validList.
Referenced by calculationResult.
void calculationResult()
Orchestrates complete calculation workflow.
Processes input through validation, tokenization, calculation, and result formatting with timing measurements. Orchestrates complete calculation workflow. Coordinates the complete calculation workflow: Input processing and cleaning Validation of mathematical expression Tokenization and parsing High-precision calculation Result formatting and timing Cleans up context after processing.
References calculate, calculationTimeFormat, getCleanInput, getRawInput, global, isValidInput, start, tokenize.
Referenced by renderGUI.
void renderCalculationProgress()
Renders real-time calculation progress in ImGui.
Displays phase-appropriate progress information including progress bars for long calculations.
References calculating, complete, error, global, validating, verifying.
void renderGUI()
Main application GUI renderer.
Creates the primary interface for input, calculation trigger, and result display using ImGui framework. Main application GUI renderer. Creates fixed-size window with multiline input field, calculate button, and result display area. Handles user interaction events and triggers calculation workflow.
References calculationResult, global, windowHeight, windowWidth.
Referenced by main.