.TH "src Directory Reference" 3 "Version 1.0" "Calc_128" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctions\&.cpp\fP"
.br
.RI "High-precision mathematical expression calculator implementation\&. "
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "Application entry point and SDL3/ImGui initialization\&. "
.in -1c
